Add german translation
kkoomen/qbr pull request #13
Opened 2021-03-21 19:25 UTC by Sematre

I really like your project and had some spare time.

2021-03-22 14:37 UTC, Kinsiinoo requested changes

2021-03-22 14:37 UTC, Kinsiinoo commented on src/translations/de.json
> +    "en": {
@Sematre That should be "de". 😉

2021-03-22 15:41 UTC, Sematre commented
Ups :facepalm:

2021-03-23 01:18 UTC, kkoomen approved these changes

2021-03-23 01:19 UTC, merged

2021-03-23 01:19 UTC, kkoomen commented
@Sematre You forgot to add the language to the README, but I'll add that. Thanks for taking the time to add the German translation.

2021-04-01 02:16 UTC, kkoomen commented
I noticed that this PR didn't add the key inside `src/constants.py`. I've just added that in the latest commit [01b45a0](https://github.com/kkoomen/qbr/commit/01b45a0b84f8037a1c33db9f0cb7b782e6013f0f).