Create fr.json
kkoomen/qbr pull request #19
Opened 2021-03-27 13:27 UTC by aitalinassim

Translation fr french

2021-03-28 14:37 UTC, Kinsiinoo requested changes
It should be "fr".

2021-03-28 14:37 UTC, Kinsiinoo commented on src/translations/fr.json
> +    "en": {
It should be "fr".
```suggestion
    "fr": {
```

2021-03-29 01:20 UTC, kkoomen approved these changes

2021-03-29 01:20 UTC, merged

2021-04-01 02:16 UTC, kkoomen commented
I noticed that this PR didn't add the key inside `src/constants.py`. I've just added that in the latest commit [01b45a0](https://github.com/kkoomen/qbr/commit/01b45a0b84f8037a1c33db9f0cb7b782e6013f0f).